In [2]:
import numpy as np

In [4]:
# arange method: Returns evenly spaced values within a given interval.
x = np.arange(-2.0, 6.0, 1)
print x

[-2. -1.  0.  1.  2.  3.  4.  5.]


In [5]:
# ones_like: Returns an array of ones with the same shape and type as a given array.
y = np.ones_like(x)
print len(x), len(y), y

8 8 [ 1.  1.  1.  1.  1.  1.  1.  1.]


In [6]:
# vstack: Stack arrays in sequence vertically (row wise).
z = np.vstack([x, y, 0.2 * y])
print z

[[-2.  -1.   0.   1.   2.   3.   4.   5. ]
 [ 1.   1.   1.   1.   1.   1.   1.   1. ]
 [ 0.2  0.2  0.2  0.2  0.2  0.2  0.2  0.2]]


In [7]:
# shape: Returns size of n-dimensional numpy array as a tuple
print z.shape

(3, 8)


In [12]:
#sum: Returns sum of array elements over a given axis.
# Sum of all elements in nd array
print np.sum(z)
# Sum of each column in nd array
print np.sum(z, axis=0)
# Sum of each row in nd array
print np.sum(z, axis=1)

21.6
[-0.8  0.2  1.2  2.2  3.2  4.2  5.2  6.2]
[ 12.    8.    1.6]


In [19]:
a = np.exp(z)
b = np.sum(np.exp(z), axis=0)
print a
print b
print a/b

[[  1.35335283e-01   3.67879441e-01   1.00000000e+00   2.71828183e+00
    7.38905610e+00   2.00855369e+01   5.45981500e+01   1.48413159e+02]
 [  2.71828183e+00   2.71828183e+00   2.71828183e+00   2.71828183e+00
    2.71828183e+00   2.71828183e+00   2.71828183e+00   2.71828183e+00]
 [  1.22140276e+00   1.22140276e+00   1.22140276e+00   1.22140276e+00
    1.22140276e+00   1.22140276e+00   1.22140276e+00   1.22140276e+00]]
[   4.07501987    4.30756403    4.93968459    6.65796642   11.32874069
   24.02522151   58.53783462  152.35284369]
[[ 0.03321095  0.08540313  0.20244208  0.40827509  0.65223985  0.8360188
   0.93269849  0.97414105]
 [ 0.66705977  0.6310485   0.55029462  0.40827509  0.23994563  0.11314284
   0.04643632  0.01784202]
 [ 0.29972928  0.28354837  0.24726331  0.18344982  0.10781452  0.05083836
   0.02086519  0.00801693]]
