In [2]:
import numpy as np

In [10]:
# ndarray: Constructor to create a n-dimensional numpy array
np.ndarray((2,3,4), dtype=np.int32)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [9]:
# zeros: Constructor to create a n-dimensional numpy array with all entries as zero
np.zeros((2,3,4), dtype=np.int32)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [4]:
# arange method: Returns evenly spaced values within a given interval.
x = np.arange(-2.0, 6.0, 1)
print x

[-2. -1.  0.  1.  2.  3.  4.  5.]


In [5]:
# ones_like: Returns an array of ones with the same shape and type as a given array.
y = np.ones_like(x)
print len(x), len(y), y

8 8 [ 1.  1.  1.  1.  1.  1.  1.  1.]


In [6]:
# vstack: Stack arrays in sequence vertically (row wise).
z = np.vstack([x, y, 0.2 * y])
print z

[[-2.  -1.   0.   1.   2.   3.   4.   5. ]
 [ 1.   1.   1.   1.   1.   1.   1.   1. ]
 [ 0.2  0.2  0.2  0.2  0.2  0.2  0.2  0.2]]


In [7]:
# shape: Returns size of n-dimensional numpy array as a tuple
print z.shape

(3, 8)


In [12]:
#sum: Returns sum of array elements over a given axis.
# Sum of all elements in nd array
print np.sum(z)
# Sum of each column in nd array
print np.sum(z, axis=0)
# Sum of each row in nd array
print np.sum(z, axis=1)

21.6
[-0.8  0.2  1.2  2.2  3.2  4.2  5.2  6.2]
[ 12.    8.    1.6]
